spring.application.name=api

server.port=8081

# ------------------------------------------------------------------

# Definição do banco.
spring.datasource.url=jdbc:postgresql://localhost:5432/sgcdb

# Driver de acesso.
spring.datasource.driver-class-name=org.postgresql.Driver

# Usuário padrão.
spring.datasource.username=postgres

# Senha padrão.
spring.datasource.password=0000

# ------------------------------------------------------------------

# 'update' atualiza automaticamente o esquema (útil para desenvolvimento).
spring.jpa.hibernate.ddl-auto=update

# Exibe as consultas SQL no console (útil para depuração).
spring.jpa.show-sql=true